### ISSUE TITLE
Use SecretValue system to store doc raptor api keys

### ISSUE THREAD

**Issue by cmacrander** [PERTS/jurassic-perts#1]
Once we have a credit card behind here, we won't want to expose our account.

https://github.com/PERTS/jurassic-perts/blob/master/docwrapper.py#L3

You can steal my SecretValue system directly from Neptune, and then use postman to POST values to the jurassic-perts datastore.

https://github.com/PERTS/neptune/blob/master/model/secretvalue.py
https://github.com/PERTS/neptune/blob/master/api_handlers.py#L1408
https://github.com/PERTS/neptune/blob/master/api_handlers.py#L1608:L1609

**Comment by mkandler** [comment]
Added to last post - using `docraptor_username` as the key
