### ISSUE TITLE
Upgrade docraptor to pipeline 5

### ISSUE THREAD

**Issue by cmacrander** [PERTS/jurassic-perts#2]
Add `pipeline: 5` to api call

https://github.com/PERTS/jurassic-perts/blob/master/jurassic_perts.py#L84

per recent blog post

https://docraptor.com/blog/pipeline-5-alive/

**Comment by mkandler** [comment]
"If not set, your documents will use Pipeline version 5 by default." - do we want to use it in this case?  I guess the argument would be whether or not we are worried about it automatically moving to new breaking versions.

**Comment by cmacrander** [comment]
Found that there's a pipeline default in account settings. I set it to 5 so we're all good. Nevermind!

<img width="1656" alt="settings" src="https://cloud.githubusercontent.com/assets/549138/20508482/d7705270-b016-11e6-87cc-d2b14611c31a.png">

**Comment by mkandler** [comment]
Oh awesome, that's even better!
